# Generated by Django 6.0.6 on 2026-06-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseoutline',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='courses.course'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cqi', to='courses.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jsu',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jsu', to='courses.course'),
        ),
        migrations.AddField(
            model_name='programme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='courses.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.programme'),
        ),
    ]
